apiVersion: v1
kind: Pod
metadata:
  name: mini-pod2
spec:
  containers:
  - name: mysql
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: ExpenseApp@1
    ports:
    - containerPort: 3306  
