apiVersion: v1
kind: Pod
metadata:
  name: preferred-affinity-min
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

