apiVersion: v1
kind: Pod
metadata:
  name: frontend-tol
spec:
  tolerations:
  - key: "disktype"
    operator: "Equal"
    value: "ssd"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx    
